version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    ports:
      - "8000:9000"
    environment:
      - APP_ENV=local
      - APP_KEY=base64:HlEunMvWYTb2woMvNvq8+p4tkE7dTlWLUaX/ilf8S6A=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=nabitu_test
      - DB_USERNAME=root
      - DB_PASSWORD=Tele123!@#

  db:
    image: mysql/mysql-server:latest
    container_name: db
    environment:
      - MYSQL_DATABASE=nabitu_test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Tele123!@#
      - MYSQL_ROOT_PASSWORD=Tele123!@#
    ports:
      - "3307:3306"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
